window.ISLANDS = [
  {
    id: "travel",
    name: "Travel",
    theme: "PLACE",
    eyebrow: "01 / PLACE",
    summary: "山野、城市与路上的片段",
    action: "Explore themes",
    emoji: "✈",
    color: "#7DA2A9",
    sprite: "assets/archive/travel.avif",
  },
  {
    id: "literature",
    name: "Literature",
    theme: "REFUGE",
    eyebrow: "02 / REFUGE",
    summary: "灵魂的避难所",
    action: "Open notes",
    emoji: "¶",
    color: "#B48A62",
    sprite: "assets/archive/literature.avif",
  },
  {
    id: "music",
    name: "Music",
    theme: "HARMONY",
    eyebrow: "03 / HARMONY",
    summary: "如果世界太危险，只有音乐最安全",
    action: "Play list",
    emoji: "♪",
    color: "#A6788C",
    sprite: "assets/archive/music.jpg",
  },
  {
    id: "film",
    name: "Film",
    theme: "VISION",
    eyebrow: "04 / VISION",
    summary: "现实的渐近线",
    action: "View frames",
    emoji: "▣",
    color: "#C16F55",
    sprite: "assets/archive/film.avif",
  },
  {
    id: "entertainment",
    name: "Entertainment",
    theme: "EXPERIENCE",
    eyebrow: "05 / EXPERIENCE",
    summary: "人生苦短，及时行乐",
    action: "Enter room",
    emoji: "＊",
    color: "#7E8677",
    sprite: "assets/archive/entertainment.avif",
  },
];
